/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CodRouteImport } from './routes/cod'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InboundRouteImport } from './routes/inbound'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OutboundRouteImport } from './routes/outbound'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ServiceTypesRouteImport } from './routes/service-types'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as ShipmentsCreateRouteImport } from './routes/shipments-create'
import { Route as SortingRouteImport } from './routes/sorting'
import { Route as StockMovementRouteImport } from './routes/stock-movement'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminCompanyRouteImport } from './routes/admin/company'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminUsersRouteImport } from './routes/admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CodRoute = CodRouteImport.update({
  id: '/cod',
  path: '/cod',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundRoute = InboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboundRoute = OutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceTypesRoute = ServiceTypesRouteImport.update({
  id: '/service-types',
  path: '/service-types',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsCreateRoute = ShipmentsCreateRouteImport.update({
  id: '/shipments-create',
  path: '/shipments-create',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const StockMovementRoute = StockMovementRouteImport.update({
  id: '/stock-movement',
  path: '/stock-movement',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompanyRoute = AdminCompanyRouteImport.update({
  id: '/admin/company',
  path: '/admin/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/billing': typeof BillingRoute
  '/cod': typeof CodRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRoute
  '/dispatch': typeof DispatchRoute
  '/documents': typeof DocumentsRoute
  '/drivers': typeof DriversRoute
  '/exceptions': typeof ExceptionsRoute
  '/help': typeof HelpRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/orders': typeof OrdersRoute
  '/outbound': typeof OutboundRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/routes': typeof RoutesRoute
  '/service-types': typeof ServiceTypesRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/shipments-create': typeof ShipmentsCreateRoute
  '/sorting': typeof SortingRoute
  '/stock-movement': typeof StockMovementRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/tracking': typeof TrackingRoute
  '/vehicles': typeof VehiclesRoute
  '/warehouses': typeof WarehousesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/billing': typeof BillingRoute
  '/cod': typeof CodRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRoute
  '/dispatch': typeof DispatchRoute
  '/documents': typeof DocumentsRoute
  '/drivers': typeof DriversRoute
  '/exceptions': typeof ExceptionsRoute
  '/help': typeof HelpRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/orders': typeof OrdersRoute
  '/outbound': typeof OutboundRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/routes': typeof RoutesRoute
  '/service-types': typeof ServiceTypesRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/shipments-create': typeof ShipmentsCreateRoute
  '/sorting': typeof SortingRoute
  '/stock-movement': typeof StockMovementRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/tracking': typeof TrackingRoute
  '/vehicles': typeof VehiclesRoute
  '/warehouses': typeof WarehousesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/billing': typeof BillingRoute
  '/cod': typeof CodRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRoute
  '/dispatch': typeof DispatchRoute
  '/documents': typeof DocumentsRoute
  '/drivers': typeof DriversRoute
  '/exceptions': typeof ExceptionsRoute
  '/help': typeof HelpRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/orders': typeof OrdersRoute
  '/outbound': typeof OutboundRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/routes': typeof RoutesRoute
  '/service-types': typeof ServiceTypesRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/shipments-create': typeof ShipmentsCreateRoute
  '/sorting': typeof SortingRoute
  '/stock-movement': typeof StockMovementRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/tracking': typeof TrackingRoute
  '/vehicles': typeof VehiclesRoute
  '/warehouses': typeof WarehousesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/billing'
    | '/cod'
    | '/contracts'
    | '/customers'
    | '/delivery'
    | '/dispatch'
    | '/documents'
    | '/drivers'
    | '/exceptions'
    | '/help'
    | '/inbound'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/maintenance'
    | '/orders'
    | '/outbound'
    | '/payments'
    | '/pricing'
    | '/profile'
    | '/reports'
    | '/returns'
    | '/routes'
    | '/service-types'
    | '/settings'
    | '/shipments'
    | '/shipments-create'
    | '/sorting'
    | '/stock-movement'
    | '/suppliers'
    | '/tasks'
    | '/tracking'
    | '/vehicles'
    | '/warehouses'
    | '/admin/audit'
    | '/admin/company'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/billing'
    | '/cod'
    | '/contracts'
    | '/customers'
    | '/delivery'
    | '/dispatch'
    | '/documents'
    | '/drivers'
    | '/exceptions'
    | '/help'
    | '/inbound'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/maintenance'
    | '/orders'
    | '/outbound'
    | '/payments'
    | '/pricing'
    | '/profile'
    | '/reports'
    | '/returns'
    | '/routes'
    | '/service-types'
    | '/settings'
    | '/shipments'
    | '/shipments-create'
    | '/sorting'
    | '/stock-movement'
    | '/suppliers'
    | '/tasks'
    | '/tracking'
    | '/vehicles'
    | '/warehouses'
    | '/admin/audit'
    | '/admin/company'
    | '/admin/roles'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/billing'
    | '/cod'
    | '/contracts'
    | '/customers'
    | '/delivery'
    | '/dispatch'
    | '/documents'
    | '/drivers'
    | '/exceptions'
    | '/help'
    | '/inbound'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/maintenance'
    | '/orders'
    | '/outbound'
    | '/payments'
    | '/pricing'
    | '/profile'
    | '/reports'
    | '/returns'
    | '/routes'
    | '/service-types'
    | '/settings'
    | '/shipments'
    | '/shipments-create'
    | '/sorting'
    | '/stock-movement'
    | '/suppliers'
    | '/tasks'
    | '/tracking'
    | '/vehicles'
    | '/warehouses'
    | '/admin/audit'
    | '/admin/company'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BillingRoute: typeof BillingRoute
  CodRoute: typeof CodRoute
  ContractsRoute: typeof ContractsRoute
  CustomersRoute: typeof CustomersRoute
  DeliveryRoute: typeof DeliveryRoute
  DispatchRoute: typeof DispatchRoute
  DocumentsRoute: typeof DocumentsRoute
  DriversRoute: typeof DriversRoute
  ExceptionsRoute: typeof ExceptionsRoute
  HelpRoute: typeof HelpRoute
  InboundRoute: typeof InboundRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OrdersRoute: typeof OrdersRoute
  OutboundRoute: typeof OutboundRoute
  PaymentsRoute: typeof PaymentsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ReturnsRoute: typeof ReturnsRoute
  RoutesRoute: typeof RoutesRoute
  ServiceTypesRoute: typeof ServiceTypesRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  ShipmentsCreateRoute: typeof ShipmentsCreateRoute
  SortingRoute: typeof SortingRoute
  StockMovementRoute: typeof StockMovementRoute
  SuppliersRoute: typeof SuppliersRoute
  TasksRoute: typeof TasksRoute
  TrackingRoute: typeof TrackingRoute
  VehiclesRoute: typeof VehiclesRoute
  WarehousesRoute: typeof WarehousesRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCompanyRoute: typeof AdminCompanyRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cod': {
      id: '/cod'
      path: '/cod'
      fullPath: '/cod'
      preLoaderRoute: typeof CodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound': {
      id: '/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbound': {
      id: '/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof OutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-types': {
      id: '/service-types'
      path: '/service-types'
      fullPath: '/service-types'
      preLoaderRoute: typeof ServiceTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments-create': {
      id: '/shipments-create'
      path: '/shipments-create'
      fullPath: '/shipments-create'
      preLoaderRoute: typeof ShipmentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-movement': {
      id: '/stock-movement'
      path: '/stock-movement'
      fullPath: '/stock-movement'
      preLoaderRoute: typeof StockMovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/company': {
      id: '/admin/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AdminCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  BillingRoute: BillingRoute,
  CodRoute: CodRoute,
  ContractsRoute: ContractsRoute,
  CustomersRoute: CustomersRoute,
  DeliveryRoute: DeliveryRoute,
  DispatchRoute: DispatchRoute,
  DocumentsRoute: DocumentsRoute,
  DriversRoute: DriversRoute,
  ExceptionsRoute: ExceptionsRoute,
  HelpRoute: HelpRoute,
  InboundRoute: InboundRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OrdersRoute: OrdersRoute,
  OutboundRoute: OutboundRoute,
  PaymentsRoute: PaymentsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ReturnsRoute: ReturnsRoute,
  RoutesRoute: RoutesRoute,
  ServiceTypesRoute: ServiceTypesRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  ShipmentsCreateRoute: ShipmentsCreateRoute,
  SortingRoute: SortingRoute,
  StockMovementRoute: StockMovementRoute,
  SuppliersRoute: SuppliersRoute,
  TasksRoute: TasksRoute,
  TrackingRoute: TrackingRoute,
  VehiclesRoute: VehiclesRoute,
  WarehousesRoute: WarehousesRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCompanyRoute: AdminCompanyRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
